/**
 * Configuración de cada módulo: API path, columnas de la tabla y campos del formulario.
 * type: 'text' | 'number' | 'date' | 'textarea' | 'select' (con `options`)
 */
export const TALLA_SELECT_OPTIONS = ['', 'M', 'L', 'S', 'XXL', 'XL', 'XXXL', 'XS', 'S-M-L-XL']

const MODULES_ORDER = [
  'dotaciones-disponibles',
  'locker-disponibles',
  'historial-retiros',
  'ingreso-lockers',
  'ingreso-dotacion',
  'base-lockers',
  'base-dotaciones',
  'registro-personal',
  'personal-presupuestado',
  'registro-asignaciones',
]

const MODULES_RAW = [
  {
    path: 'base-lockers',
    title: 'Base de Lockers',
    icon: '📦',
    apiPath: '/api/base-lockers',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'area', label: 'Área' },
      { key: 'area_lockers', label: 'Área Lockers' },
      { key: 'estado', label: 'Estado' },
      { key: 'unidad', label: 'Unidad' },
    ],
    formFields: [
      { name: 'codigo', label: 'Código', type: 'text', required: true },
      { name: 'area', label: 'Área', type: 'text' },
      { name: 'area_lockers', label: 'Área Lockers', type: 'text' },
      { name: 'estado', label: 'Estado', type: 'text' },
      { name: 'unidad', label: 'Unidad', type: 'text' },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
  },
  {
    path: 'locker-disponibles',
    title: 'Locker Disponibles',
    icon: '🔓',
    apiPath: '/api/locker-disponibles',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'area', label: 'Área' },
      { key: 'area_lockers', label: 'Área Lockers' },
      { key: 'estado', label: 'Estado' },
    ],
    formFields: [
      { name: 'codigo', label: 'Código', type: 'text', required: true },
      { name: 'area', label: 'Área', type: 'text' },
      { name: 'area_lockers', label: 'Área Lockers', type: 'text' },
      { name: 'estado', label: 'Estado', type: 'text' },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
  },
  {
    path: 'base-dotaciones',
    title: 'Base de Dotaciones',
    icon: '📋',
    apiPath: '/api/base-dotaciones',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'cantidad', label: 'Cantidad' },
      { key: 'talla', label: 'Talla' },
      { key: 'estado', label: 'Estado' },
    ],
    formFields: [
      { name: 'codigo', label: 'Código', type: 'text' },
      { name: 'cantidad', label: 'Cantidad', type: 'number' },
      { name: 'area_uso', label: 'Área uso', type: 'text' },
      { name: 'talla', label: 'Talla', type: 'select', options: TALLA_SELECT_OPTIONS },
      { name: 'estado', label: 'Estado', type: 'text' },
    ],
  },
  {
    path: 'dotaciones-disponibles',
    title: 'Dotaciones Disponibles',
    icon: '✅',
    apiPath: '/api/dotaciones-disponibles',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'talla', label: 'Talla' },
      { key: 'cantidad', label: 'Cantidad' },
    ],
    formFields: [
      { name: 'codigo', label: 'Código', type: 'text' },
      { name: 'talla', label: 'Talla', type: 'select', options: TALLA_SELECT_OPTIONS },
      { name: 'cantidad', label: 'Cantidad', type: 'number' },
    ],
  },
  {
    path: 'registro-personal',
    title: 'Registro de Personal',
    icon: '👤',
    apiPath: '/api/registro-personal',
    columns: [
      { key: 'id_personal', label: 'ID Personal' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'documento', label: 'Documento' },
      { key: 'area', label: 'Área' },
    ],
    formFields: [
      { name: 'id_personal', label: 'ID Personal', type: 'text' },
      { name: 'nombre', label: 'Nombre', type: 'text' },
      { name: 'documento', label: 'Documento', type: 'text' },
      { name: 'area', label: 'Área', type: 'text' },
      { name: 'talla', label: 'Talla', type: 'select', options: TALLA_SELECT_OPTIONS },
      { name: 'area_lockers', label: 'Área Lockers', type: 'text' },
      { name: 'estado', label: 'Estado', type: 'text' },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
  },
  {
    path: 'personal-presupuestado',
    title: 'Personal Presupuestado',
    icon: '📊',
    apiPath: '/api/personal-presupuestado',
    columns: [
      { key: 'nombre', label: 'Nombre' },
      { key: 'documento', label: 'Documento' },
      { key: 'cargo', label: 'Cargo' },
      { key: 'area', label: 'Área' },
      { key: 'aprobados', label: 'Aprobados' },
      { key: 'contratados', label: 'Contratados' },
      { key: 'por_contratar', label: 'Por contratar' },
    ],
    formFields: [
      { name: 'nombre', label: 'Nombre', type: 'text' },
      { name: 'documento', label: 'Documento', type: 'text' },
      { name: 'cargo', label: 'Cargo', type: 'text' },
      { name: 'area', label: 'Área', type: 'text' },
      { name: 'aprobados', label: 'Aprobados', type: 'number' },
      { name: 'contratados', label: 'Contratados', type: 'number' },
      { name: 'por_contratar', label: 'Por contratar', type: 'number' },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
  },
  {
    path: 'registro-asignaciones',
    title: 'Registro de Asignaciones',
    icon: '🔗',
    apiPath: '/api/registro-asignaciones',
    hideCreate: true,
    columns: [
      { key: 'identificacion', label: 'Identificación' },
      { key: 'operario', label: 'Operario' },
      { key: 'area', label: 'Área' },
      { key: 'talla_operarios', label: 'Talla' },
      { key: 'talla_dotacion', label: 'Talla Dotación Asignada' },
      { key: 'area_lockers', label: 'Área de Lockers' },
      { key: 'codigo_dotacion', label: 'Cód. Dotación' },
      { key: 'codigo_lockets', label: 'Cód. Lockers' },
      { key: 'codigo_seca_botas', label: 'Cód. Seca Botas' },
      { key: 'fecha_entrega', label: 'Fecha de Entrega' },
      { key: 'estado', label: 'Estado' },
    ],
    formFields: [
      { name: 'codigo_dotacion', label: 'Código dotación', type: 'text' },
      { name: 'fecha_asignacion', label: 'Fecha asignación', type: 'date' },
      { name: 'fecha_entrega', label: 'Fecha entrega', type: 'date' },
      { name: 'operario', label: 'Operario', type: 'text' },
      { name: 'identificacion', label: 'Identificación', type: 'text', required: true },
      { name: 'codigo_lockets', label: 'Código lockers', type: 'text' },
      { name: 'codigo_seca_botas', label: 'Código seca botas', type: 'text' },
      { name: 'area', label: 'Área', type: 'text' },
      { name: 'talla_operarios', label: 'Talla operarios', type: 'select', options: TALLA_SELECT_OPTIONS },
      { name: 'talla_dotacion', label: 'Talla dotación', type: 'select', options: TALLA_SELECT_OPTIONS },
      { name: 'area_lockers', label: 'Área lockers', type: 'text' },
      { name: 'estado', label: 'Estado', type: 'select', options: ['', 'ACTIVO', 'INACTIVO', 'PENDIENTE'] },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
  },
  {
    path: 'historial-retiros',
    title: 'Historial de Retiros',
    icon: '📤',
    apiPath: '/api/historial-retiros',
    columns: [
      { key: 'operario', label: 'Operario' },
      { key: 'codigo_dotacion', label: 'Cód. Dotación' },
      { key: 'fecha_retiro', label: 'Fecha retiro' },
    ],
    formFields: [
      { name: 'identificacion', label: 'Identificación', type: 'text' },
      { name: 'codigo_dotacion', label: 'Código dotación', type: 'text' },
      { name: 'fecha_retiro', label: 'Fecha retiro', type: 'date' },
      { name: 'operario', label: 'Operario', type: 'text' },
      { name: 'codigo_lockets', label: 'Código lockers', type: 'text' },
      { name: 'area', label: 'Área', type: 'text' },
      { name: 'talla_operarios', label: 'Talla operarios', type: 'select', options: TALLA_SELECT_OPTIONS },
      { name: 'talla_dotacion', label: 'Talla dotación', type: 'select', options: TALLA_SELECT_OPTIONS },
      { name: 'area_lockers', label: 'Área lockers', type: 'text' },
    ],
  },
  {
    path: 'ingreso-lockers',
    title: 'Ingreso de Lockers',
    icon: '➕',
    apiPath: '/api/ingreso-lockers',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'cantidad', label: 'Cantidad' },
      { key: 'fecha_ingreso', label: 'Fecha ingreso' },
    ],
    formFields: [
      { name: 'codigo', label: 'Código', type: 'text' },
      { name: 'cantidad', label: 'Cantidad', type: 'number' },
      { name: 'fecha_ingreso', label: 'Fecha ingreso', type: 'date' },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
  },
  {
    path: 'ingreso-dotacion',
    title: 'Ingreso de Dotación',
    icon: '📥',
    apiPath: '/api/ingreso-dotacion',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'descripcion', label: 'Descripción' },
      { key: 'cantidad', label: 'Cantidad' },
      { key: 'fecha_ingreso', label: 'Fecha ingreso' },
    ],
    formFields: [
      { name: 'codigo', label: 'Código', type: 'text' },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
      { name: 'cantidad', label: 'Cantidad', type: 'number' },
      { name: 'fecha_ingreso', label: 'Fecha ingreso', type: 'date' },
      { name: 'observaciones', label: 'Observaciones', type: 'textarea' },
    ],
  },
]

export const MODULES = MODULES_ORDER.map((path) => MODULES_RAW.find((m) => m.path === path))

export function getModuleByPath(path) {
  return MODULES.find((m) => m.path === path) || null
}
